### PR TITLE
Initial county geojson

### PR DESCRIPTION
**Pull request by mdelcambre**
Adds the initial geojson file for each of the surrounding counties. Addresses data part of #101. Will need to add the feature to the map.

at the time of PR I did rebase with all master changes.

### CODE REVIEW

**Comment by alulsh** [comment]
Whoohoo! What do the numbers in the filenames mean @mdelcambre? For example, `Alexandria510.geojson` has the number `510`? Can you rename to not have numbers and not have punctuation? 

e.g.  `Prince George's033.geojson` > `PrinceGeorges.geojson`

**Comment by mdelcambre** [comment]
Sure I can do that.
They are the Census FIPS code, mainly to separate Fairfax and Fairfax. Will get those cleaned up.

**Comment by mdelcambre** [comment]
Should be good to go.

**Comment by alulsh** [comment]
This is awesome! Thanks @mdelcambre! Next step is for us to add these to the Mapbox GL JS map! Will merge for now though so we have the data available.

**Pull request merged**
