### PR TITLE
Added Fairfax, VA

### PR DESCRIPTION
**Pull request by alongthepike**
Added infrastructure GeoJson, Buffer GeoJson, added fetch logic to fetch script and updated the main script file & html to display Fairfax.

### CODE REVIEW

**Comment by alongthepike** [comment]
This should satisfy #41

**Comment by alulsh** [comment]
@alongthepike - per my coworker @k-mahoney who bikes a lot in Fairfax County, it looks like the data from ffx county includes sharrows.

@alongthepike @nellepierson - what should we do? should we include this data even though it includes sharrows?

**Comment by alongthepike** [comment]
Can @k-mahoney be more specific?  Which roads?  Fairfax has added a lot of bike lanes recently.  I'm quite confident that I'm appropriately filtering based on what the data says.  If we know specific data that is wrong I can pass that along to Fairfax County.

Here is a visualization of just the "bike lanes" from the Fairfax GIS: https://gist.github.com/anonymous/601ac50218d0e6a6f8a89eb9c7db0eda

**Comment by k-mahoney** [comment]
Hey @alongthepike -- The routes with sharrows may be limited to Fairfax City, the road I specifically noticed upon first review was University Drive. As the county and city are two different jurisdictions, it may be an issue with how the city reported its data rather than the county as a whole.

**Comment by alongthepike** [comment]
Thanks @k-mahoney -- yeah, for some reason University Drive is listed as a "Paved Trail" in Fairfax's bike data.  I'll report it to them!

**Comment by alulsh** [comment]
Despite the Fairfax City issue above I'm going to merge this 🎉  - we can create a separate GitHub issue for it. Will merge manually from the command line.

**Comment by k-mahoney** [comment]
@alongthepike it does have, for a small segment of it, a paved side path in addition to the sharrows- probably why it's labeled that way.

**Comment by alulsh** [comment]
Yay! So happy to be merging this 😎 . Fixes https://github.com/dcfemtech/hackforgood-waba-map/issues/41.

@alongthepike @k-mahoney mind creating a new data quality issue to track the Fairfax City issues?  Just created a new `data` label too to make it easier to keep track of these.

**Pull request merged**
