### PR TITLE
Added Prince George's County Maryland

### PR DESCRIPTION
**Pull request by alongthepike**
Added Prince George's County Maryland based on the available shape file.  I filtered it down to only Existing facility (not planned) and only Bike Lanes and Hard Surface Trails (not shoulders, sidepaths or dirt trails). As requested in #10 

My first ever pull request on Github, please be gentle ;)

### CODE REVIEW

**Comment by alulsh** [comment]
Thanks for adding the PG county data for us @alongthepike! This is huge. The bike lane PG county data looks great. Thanks for filtering Montgomery County to remove the sharrows too.

The buffers for PG county don't appear to be loading correctly the preview on Github though - instead I see a map of the world per the screenshot below. Even when I zoom in on the DC area I don't see any buffers.

Once you fix the buffers I'll merge this!

screenshot 2016-08-01 00 16 37

**Comment by alulsh** [comment]
Rethinking this - once we have 100% reliable data coverage for the region (possibly disregarding Fairfax County) - we'll create pre-generated buffers for the entire region, not just on a per county basis.

If you delete the buffers for PG county from this PR then we are good to go and I can merge. I can create an issue to create buffers for the entire region (instead of on a per county/city basis) once we are feeling great about the available data.

**Comment by NealHumphrey** [comment]
@alulsh - I spent some time yesterday trying to see if I could come up with a way to run the buffer calculation client-side with a reasonable calculation time, but couldn't get it to work. I will instead plan to put these calculations into an admin function we can call to recalculate the buffers whenever needed. That way we have the recalculate code easily accessible so that it's not a big deal to generate new buffers whenever we have updated data.

**Comment by alongthepike** [comment]
Closing this - will do a new pull request from a feature branch without the buffers (which are in the wrong projection)

**Pull request closed without merging**
