### PR TITLE
Issue101 Adds County Lines 

### PR DESCRIPTION
**Pull request by mdelcambre**
County lines will now display. 

Also noticed that buffers were not in agreement with the buffer filenames and fixed.

### CODE REVIEW

**Comment by alulsh** [comment]
Yay! This look great but is missing Fairfax County in the UI - can you add as well even though there is no bike lane data displayed yet?

**Comment by mdelcambre** [comment]
Sure, likely won't be until tomorrow. I think it will require a bit of refactoring since we have assumed that the regions will have all attributes. 

Additionally as an FYI this branch will not work right now, since we use the master branch for the geojson and it has the old names.

**Comment by alulsh** [comment]
> Sure, likely won't be until tomorrow. I think it will require a bit of refactoring since we have assumed that the regions will have all attributes.

Ah, I see! If it ends up being too much of a hassle to deal with the attributes then I can merge this and we can make the Fairfax County geojson a GitHub separate issue to tackle after we add the bikelane data. Let me know what you think tomorrow.

> Additionally as an FYI this branch will not work right now, since we use the master branch for the geojson and it has the old names.

I got around this by temporarily renaming `var countyUrl = 'https://raw.githubusercontent.com/dcfemtech/hackforgood-waba-map/master/counties/';` to `var countyUrl = 'https://raw.githubusercontent.com/dcfemtech/hackforgood-waba-map/Issue101/counties/';` when testing locally 😉 .

Also, I'm going to look into just using local files later this week - i.e. `fairfaxcounty.geojson` instead of `https://raw.githubusercontent.com/dcfemtech/hackforgood-waba-map/master/counties/fairfaxcounty.geojson`.

**Comment by mdelcambre** [comment]
Should be good to go. It will throw one null error in the console, but doesn't impact the performance. 

Additionally I am cheating a bit on Falls Church and Fairfax City. Since we are only showing outline, I am not loading those files. It makes no difference since they share a boundary on all sides with one our other county files.

**Comment by alulsh** [comment]
This is awesome @mdelcambre!! Merging 😎 .

**Pull request merged**
